name: Deploy Gatsby site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_ENV
            echo "command=install" >> $GITHUB_ENV
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_ENV
            echo "command=ci" >> $GITHUB_ENV
          else
            echo "Unable to determine package manager" && exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: ${{ env.manager }}

      - name: Install dependencies
        run: ${{ env.manager }} ${{ env.command }}

      - name: Build with Gatsby
        env:
          PREFIX_PATHS: 'true'
        run: ${{ env.manager }} run build

      - name: Verify public directory
        run: |
          echo "Contents of public directory:"
          ls -la public
          echo "Directory size:"
          du -sh public

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gatsby-build
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: gatsby-build
          path: public

      - name: Verify downloaded artifact
        run: |
          echo "Contents of downloaded public directory:"
          ls -la public
          echo "Directory size after download:"
          du -sh public

      - name: Check for symlinks
        run: |
          echo "Checking for symlinks in public directory:"
          find public -type l -exec ls -la {} \;

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: gatsby-build
